************* Module combined
combined.py:528:0: C0304: Final newline missing (missing-final-newline)
combined.py:1:0: C0114: Missing module docstring (missing-module-docstring)
combined.py:74:25: C0103: Argument name "df" doesn't conform to snake_case naming style (invalid-name)
combined.py:126:0: W0102: Dangerous default value {} as argument (dangerous-default-value)
combined.py:166:34: W0108: Lambda may not be necessary (unnecessary-lambda)
combined.py:197:0: W0105: String statement has no effect (pointless-string-statement)
combined.py:202:0: W0404: Reimport 're' (imported line 1) (reimported)
combined.py:202:0: C0413: Import "import re" should be placed at the top of the module (wrong-import-position)
combined.py:203:0: E0401: Unable to import 'emoji' (import-error)
combined.py:203:0: C0413: Import "import emoji" should be placed at the top of the module (wrong-import-position)
combined.py:204:0: C0413: Import "import nltk" should be placed at the top of the module (wrong-import-position)
combined.py:205:0: W0404: Reimport 'pandas' (imported line 3) (reimported)
combined.py:205:0: C0413: Import "import pandas as pd" should be placed at the top of the module (wrong-import-position)
combined.py:207:0: W0404: Reimport 'SentimentIntensityAnalyzer' (imported line 8) (reimported)
combined.py:207:0: C0413: Import "from nltk.sentiment import SentimentIntensityAnalyzer" should be placed at the top of the module (wrong-import-position)
combined.py:208:0: W0404: Reimport 'ConfusionMatrixDisplay' (imported line 9) (reimported)
combined.py:208:0: C0413: Import "from sklearn.metrics import ConfusionMatrixDisplay" should be placed at the top of the module (wrong-import-position)
combined.py:209:0: E0401: Unable to import 'textblob' (import-error)
combined.py:209:0: C0413: Import "from textblob import TextBlob" should be placed at the top of the module (wrong-import-position)
combined.py:210:0: E0401: Unable to import 'transformers' (import-error)
combined.py:210:0: C0413: Import "from transformers import pipeline" should be placed at the top of the module (wrong-import-position)
combined.py:215:0: E0102: function already defined line 14 (function-redefined)
combined.py:368:8: R1705: Unnecessary "else" after "return", remove the "else" and de-indent the code inside it (no-else-return)
combined.py:458:4: R0913: Too many arguments (6/5) (too-many-arguments)
combined.py:202:0: C0411: standard import "import re" should be placed before "import numpy as np" (wrong-import-order)
combined.py:205:0: C0412: Imports from package pandas are not grouped (ungrouped-imports)
combined.py:207:0: C0412: Imports from package nltk are not grouped (ungrouped-imports)
combined.py:208:0: C0412: Imports from package sklearn are not grouped (ungrouped-imports)

------------------------------------------------------------------
Your code has been rated at 7.35/10 (previous run: 0.00/10, +7.35)

